#!/bin/bash
if [ ! "$(command -v docker)" ]; then
    echo "docker could not be found"
    exit 0
fi

dir=$(pwd)

NAME=api
HOST=pg
NETWORK_NAME=node-network

if [ ! "$(docker network ls | grep "$NETWORK_NAME")" ]; then
  echo "Creating network ..."
  docker network create $NETWORK_NAME
fi

docker run --rm -it -v $dir:/opt/ -w /opt/ --name $NAME --net $NETWORK_NAME -e HOST=$HOST node:18.19.0-buster node Api/index.ts