version: '3.8'

services:
  pg:
    image: postgres:12
    environment:
      POSTGRES_DB: mydb
      POSTGRES_USER: myuser
      POSTGRES_PASSWORD: mypassword
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - mynet

    build: 
      image: node:18.19.0-buster
      volumes:
        - .:/app
      working_dir: /app
      command: npm i
      networks:
        - mynet
      
